### ISSUE TITLE
Doesn't work import

### ISSUE THREAD

**Issue by Tilesto** [VirtoCommerce/vc-module-catalog-csv-import#18]
What's wrong with ~~me~~ csv module?
I select few products, export this in csv-file.
Then i click "import" and select our exported file => Errors, import doesn't work.
What am I doing wrong? 
And question two: what's type of delimiter used by default in Virto export?

Video: http://recordit.co/7P8bJ6ycJN

**Comment by tatarincev** [comment]
Browser: Chrome 68
OS: Windows 10

Steps to reproduce:

Open demo site or on any development environment .
Try to do export for any category from Catalog module with csv file.
Import same csv file.
Expected results:
File will be imported with errors (duplicated ids ).

Current results:
File is imported with exception:
FluentValidation.ValidationException: Validation failed:
-- 'Name' should not be empty.

Example of file is here

**Comment by sansey2k** [comment]
Reproduced defect on dev env with changed settings 
https://pm-admin-qc.azurewebsites.net/#/workspace/settings
Admin/store

The following exception received:
FluentValidation.ValidationException: Validation failed: 
 -- 'Name' should not be empty.
 at VirtoCommerce.CatalogModule.Data.Services.CategoryServiceImpl.ValidateCategoryProperties(Category[] categories)
 at VirtoCommerce.CatalogModule.Data.Services.CategoryServiceImpl.SaveChanges(Category[] categories)
 at VirtoCommerce.CatalogModule.Data.Services.CategoryServiceImpl.Create(Category category)
 at VirtoCommerce.CacheModule.Data.Decorators.CatalogServicesDecorator.Create(Category category)
 at VirtoCommerce.CatalogCsvImportModule.Data.Services.CsvCatalogImporter.SaveCategoryTree(Catalog catalog, IEnumerable`1 csvProducts, ExportImportProgressInfo progressInfo, Action`1 progressCallback)
 at VirtoCommerce.CatalogCsvImportModule.Data.Services.CsvCatalogImporter.DoImport(List`1 csvProducts, CsvImportInfo importInfo, ExportImportProgressInfo progressInfo, Action`1 progressCallback)
 at VirtoCommerce.CatalogCsvImportModule.Data.Services.CsvCatalogImporter.DoImport(Stream inputStream, CsvImportInfo importInfo, Action`1 progressCallback)
 at VirtoCommerce.CatalogCsvImportModule.Web.Controllers.Api.ExportImportController.BackgroundImport(CsvImportInfo importInfo, ImportNotification notifyEvent)

**Comment by sansey2k** [comment]
Trying to import 2 items just exported from same sub category.
The following exception is received.

![image](https://user-images.githubusercontent.com/21069289/46346583-c5023000-c648-11e8-87b6-7eb1b936dc8f.png)
Exported file is attached
[2 items.zip](https://github.com/VirtoCommerce/vc-module-catalog-csv-import/files/2437663/2.items.zip)
